serial:
  port: COM3  # Puerto serie Arduino (ajustar según tu sistema)
  baudrate: 9600
  timeout: 1.0
  pins:
    rx: 2  # Pin digital 2 para RX
    tx: 3  # Pin digital 3 para TX

sensors:
  - name: temperature
    type: analog
    pin: A0
    units: celsius
    
  - name: humidity
    type: analog
    pin: A1
    units: percentage
    
  - name: light
    type: analog
    pin: A2
    units: lux

reading:
  interval: 1.0  # Intervalo de lectura en segundos
  log_file: sensor_data.csv
